server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://CCADLG@bitbucket.org/ccadlg/config-data.git
          search-paths: api
          default-label: "master"
          
  security:
    user:
      name: root
      password: 123
